name: 'Build and deploy to MRT'

on:
  workflow_dispatch:
    inputs:
      deployment_message:
        description: 'Deployment message'
        required: true
        default: 'CI build'
      target_slug:
        description: 'Target slug'
        required: true
        default: 'sfra-ci'
      target_url:
        description: 'Target URL'
        required: true
        default: 'https://transition-kit-sfra-ci.mobify-storefront.com/'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # These environment variables must be changed to fit your PWA Kit project.
    env:
      PROJECT_SLUG: 'transition-kit'
      SLACK_CHANNEL: 'uki-pwa-transition-kit'

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm

      - name: Install application's dependencies
        run: npm ci

      # These tokens are to be stored into your GitHub Repository Settings
      # Security > Secrets > Actions > New Repository Secret
      # - `MRT_API_USER` is your Managed Runtime username (...maybe you'd want to ask IT a dedicated username instead of yours...)
      # - `MRT_API_TOKEN` is your Managed Runtime API token
      # Both can be found into your Managed Runtime Account Settings, top right.
      - name: Save credentials
        run: npm run save-credentials -- --user ${{secrets.MRT_API_USER}} --key ${{secrets.MRT_API_TOKEN}}

      - name: Push the bundle to MRT
        run: npm run push -- -m "${{github.event.inputs.deployment_message}}"

      - name: Get the bundle ID
        run: |
          curl "https://cloud.mobify.com/api/projects/${{ env.PROJECT_SLUG }}/bundles/" \
            -H "Authorization: Bearer ${{ secrets.MRT_API_TOKEN}}" \
            -H "Content-Type: application/json" \
            -o "bundle.json"
     # jq is used to parse the JSON output of the previous command and retreive the bundle ID.
      # You can find more information about jq here: https://stedolan.github.io/jq/
      # - `cmd` is the command that will be executed
      # - `bundle.json` is the file that contains the JSON output of the previous command
      # - `-r` is used to indicate that the output of the command should be read as a string
      # - `outputs.value` is the name of the output that will be stored in the workflow's context
      # - `value` is the name of the variable
      - name: Store the bundle ID
        uses: sergeysova/jq-action@v2
        id: store-bundle-id
        with:
          cmd: 'jq .results[0].id bundle.json -r'

      - name: Read and deploy the bundle ID
        run: |
            curl 'https://cloud.mobify.com/api/projects/${{ env.PROJECT_SLUG }}/target/${{ github.event.inputs.target_slug }}/deploy/' \
              --request 'POST' \
              --header "Authorization: Bearer ${{ secrets.MRT_API_TOKEN}}" \
              --header 'Content-Type: application/json' \
              --data '{"bundle_id": "${{ steps.store-bundle-id.outputs.value }}"}'
      - name: Notify Slack channel
        run: |
          curl \
            -X POST \
            https://slack.com/api/chat.postMessage \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN}}" \
            --data '{ "channel": "${{ env.SLACK_CHANNEL }}", "unfurl_links": false, "unfurl_media": false, "blocks": [{ "type": "context", "elements": [{ "type": "mrkdwn", "text": " Deployment with the name `${{github.event.inputs.deployment_message}}` was deployed to ${{github.event.inputs.target_url}} by ${{github.event.actor.login}}" }, { "type": "image", "image_url": "${{github.event.actor.avatar_url}}", "alt_text": "images" }]}, { "type": "context", "elements": [{ "type": "mrkdwn", "text": "*Title: ${{github.event.inputs.deployment_message}}*" }]}, { "type": "context", "elements": [{ "type": "mrkdwn", "text": ":white_check_mark: Deployed Bundle ${{steps.store-bundle-id.outputs.value}} to <${{ github.event.inputs.target_url }}|${{ github.event.inputs.target_slug }}>" }]}, { "type": "actions", "elements": [{ "type": "button", "text": { "type": "plain_text", "text": "View in GitHub" }, "style": "primary", "url": "/" }]}]}'
